In [5]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
import numpy as np
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import cross_val_score
import joblib


In [6]:
import pandas as pd
from sentence_transformers import SentenceTransformer

# Ejemplo de frases en español
frases = [
    'La programación es una habilidad clave en el mundo laboral actual.',
    'El trabajo en equipo es fundamental en el desarrollo de proyectos de programación.',
    'La industria tecnológica ofrece numerosas oportunidades laborales en el campo de la programación.',
    'La programación es una forma creativa de resolver problemas.',
    'La actualización constante de habilidades es esencial en el ámbito de la programación.',
    'La práctica regular de deporte mejora la salud física y mental.',
    'Una alimentación balanceada es fundamental para mantener una buena salud.',
    'El deporte ayuda a reducir el estrés y mejorar el estado de ánimo.',
    'La salud es un tesoro que debemos cuidar y valorar.',
    'El deporte es una actividad divertida que nos permite mantenernos en forma.',
    'Amo a mi perro con toda mi vida',
    'Mi mascota es lo mejor que me ha sucedido'

]

# Crear el DataFrame
df = pd.DataFrame({'frases': frases})

# Cargar el modelo SentenceTransformer
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

# Obtener las representaciones de las frases
embeddings = model.encode(df['frases'].tolist())

# Convertir las representaciones en un DataFrame
embeddings_df = pd.DataFrame(embeddings)

# Concatenar el DataFrame original con las representaciones
df_concatenated = pd.concat([df, embeddings_df], axis=1)

# Imprimir el DataFrame con las representaciones concatenadas
df_concatenated.head(2)

frases         0         1   
0  La programación es una habilidad clave en el m... -0.213440 -0.069173  \
1  El trabajo en equipo es fundamental en el desa... -0.196377 -0.179967   

          2         3         4         5         6         7         8  ...   
0 -0.197310 -0.029537 -0.130899  0.094700 -0.013937 -0.065587 -0.128986  ...  \
1 -0.068353 -0.064427 -0.267967 -0.021664 -0.277520 -0.026893  0.128443  ...   

        374       375       376       377       378       379       380   
0 -0.011848  0.112096  0.110057 -0.194281  0.122164  0.201293 -0.263372  \
1  0.265531  0.452463  0.059066 -0.019282  0.238384 -0.043932 -0.224611   

        381       382       383  
0  0.073772  0.209616 -0.065574  
1  0.203272  0.220722 -0.301896  

[2 rows x 385 columns]

In [8]:
# Aplicar el algoritmo K-means
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(embeddings)

# Agregar los clusters al DataFrame
df['cluster'] = clusters

# Imprimir el DataFrame con los clusters
df.head(12)

c:\Users\jcasas\AppData\Local\anaconda3\envs\Rotacion\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


frases  cluster
0   La programación es una habilidad clave en el m...        2
1   El trabajo en equipo es fundamental en el desa...        2
2   La industria tecnológica ofrece numerosas opor...        2
3   La programación es una forma creativa de resol...        2
4   La actualización constante de habilidades es e...        2
5   La práctica regular de deporte mejora la salud...        1
6   Una alimentación balanceada es fundamental par...        1
7   El deporte ayuda a reducir el estrés y mejorar...        1
8   La salud es un tesoro que debemos cuidar y val...        1
9   El deporte es una actividad divertida que nos ...        1
10                    Amo a mi perro con toda mi vida        0
11          Mi mascota es lo mejor que me ha sucedido        0

In [7]:
import pandas as pd
from sentence_transformers import SentenceTransformer

# Ejemplo de frases en español
frases = [
    'La programación es una habilidad clave en el mundo laboral actual.',
    'La práctica regular de deporte mejora la salud física y mental.',
    'El trabajo en equipo es fundamental en el desarrollo de proyectos de programación.',
    'Una alimentación balanceada es fundamental para mantener una buena salud.',
    'La industria tecnológica ofrece numerosas oportunidades laborales en el campo de la programación.',
    'El deporte ayuda a reducir el estrés y mejorar el estado de ánimo.',
    'La programación es una forma creativa de resolver problemas.',
    'La salud es un tesoro que debemos cuidar y valorar.',
    'La actualización constante de habilidades es esencial en el ámbito de la programación.',
    'El deporte es una actividad divertida que nos permite mantenernos en forma.'
]

# Crear el DataFrame
df = pd.DataFrame({'frases': frases})

# Cargar el modelo SentenceTransformer
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

# Obtener las representaciones de las frases
embeddings = model.encode(df['frases'].tolist())

# Convertir las representaciones en un DataFrame
embeddings_df = pd.DataFrame(embeddings)

# Concatenar el DataFrame original con las representaciones
df_concatenated = pd.concat([df, embeddings_df], axis=1)

# Aplicar el algoritmo K-means
kmeans = KMeans(n_clusters=2, random_state=42)
clusters = kmeans.fit_predict(embeddings)

# Agregar los clusters al DataFrame
df['cluster'] = clusters

# Imprimir el DataFrame con los clusters
df.head(10)

c:\Users\jcasas\AppData\Local\anaconda3\envs\Rotacion\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


frases  cluster
0  La programación es una habilidad clave en el m...        0
1  La práctica regular de deporte mejora la salud...        1
2  El trabajo en equipo es fundamental en el desa...        0
3  Una alimentación balanceada es fundamental par...        1
4  La industria tecnológica ofrece numerosas opor...        0
5  El deporte ayuda a reducir el estrés y mejorar...        1
6  La programación es una forma creativa de resol...        0
7  La salud es un tesoro que debemos cuidar y val...        1
8  La actualización constante de habilidades es e...        0
9  El deporte es una actividad divertida que nos ...        1

In [10]:

k_means_training(df_train, 100)
kmeans_model = joblib.load('Clustering/Models/K_means/kmeans_model_BERT.pkl')
labels = kmeans_model.labels_


[3, 2, 4]
3


In [11]:
labels

array([0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 1, 1, 1, 1, 1, 2, 0, 1, 2, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       2, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1,
       0, 2, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 2, 2, 1, 2, 1, 1, 2, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 2, 1, 1, 1, 1, 0, 0, 1, 2, 2, 1,
       2, 1, 2, 2, 0, 2, 1, 2, 1, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 1, 1, 1,
       1, 2, 0, 0, 0, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 2,
       1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       0, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 2, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 2, 1, 2, 0, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1,
       1, 0, 1, 2, 0, 0, 2, 1, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 2, 2,
       2, 1, 0, 0, 0, 1, 2, 0, 2, 1, 0, 1, 1, 0, 0, 0, 2, 0, 1, 2, 0, 0,
       0, 2, 2, 0, 0, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2,

In [18]:
# Agregar los resultados de la clusterización al DataFrame original
df['cluster'] = labels

# Crear una figura 3D interactiva con Plotly
fig = go.Figure(data=[go.Scatter3d(
    x=embeddings_3d[:, 0],
    y=embeddings_3d[:, 1],
    z=embeddings_3d[:, 2],
    mode='markers',
    marker=dict(
        size=5,
        color=labels,
        colorscale='Viridis',
        opacity=0.8
    )
)])

# Configurar el título y los ejes
fig.update_layout(
    title='Clusters',
    scene=dict(
        xaxis_title='Dimensión 1',
        yaxis_title='Dimensión 2',
        zaxis_title='Dimensión 3'
    )
)

# Mostrar la figura
fig.show()


NameError: name 'embeddings_3d' is not defined

In [12]:
from sklearn.decomposition import PCA

# Reducción de dimensionalidad con PCA a 2D
pca = PCA(n_components=2, random_state=0)
embeddings_2d = pca.fit_transform(df_train)

# Agregar los resultados de la clusterización al DataFrame original
df_train['Clusters'] = labels
df_features['Clusters'] = labels

# Crear una figura 2D interactiva con Plotly
fig = go.Figure(data=[go.Scatter(
    x=embeddings_2d[:, 0],
    y=embeddings_2d[:, 1],
    mode='markers',
    marker=dict(
        size=5,
        color=labels,
        colorscale='Viridis',
        opacity=0.8
    )
)])

# Configurar el título y los ejes
fig.update_layout(
    title='Clusters',
    xaxis_title='Componente Principal 1',
    yaxis_title='Componente Principal 2'
)

# Mostrar la figura
fig.show()


In [15]:
df_train = df_train.drop(["Año_ingreso", "Año_retiro", "cluster"], axis=1)

In [16]:
df_train.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       'PAULO PEREZ_JEFE', 'RAFAEL PINO_JEFE', 'RENE LOZADA_JEFE',
       'ROCIO CORREA_JEFE', 'RODRIGO TORRES_JEFE', 'ROLPHY QUINTERO_JEFE',
       'STEPHEN PINTO_JEFE', 'TATIANA ROJAS_JEFE', 'VICTOR SANTAFE_JEFE',
       'Clusters'],
      dtype='object', length=704)

# Random Forest

In [20]:
# Obtener los datos de las variables (excluyendo las etiquetas de los clusters)
X = df_features.drop('Clusters', axis=1)  # Reemplaza 'Cluster' con el nombre de tu columna de etiquetas

# Obtener las etiquetas de los clusters
y = df_features['Clusters']  # Reemplaza 'Cluster' con el nombre de tu columna de etiquetas

# Separar los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=96)

# Crear el modelo de Random Forest
rf = RandomForestClassifier(random_state=96)

# Entrenar el modelo con los datos
rf.fit(X, y)

# Realizar predicciones en el conjunto de prueba
y_pred = rf.predict(X_test)

# Calcular la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo:", accuracy)

# Generar un informe de clasificación
report = classification_report(y_test, y_pred)
print("Informe de clasificación:")
print(report)


# Realizar validación cruzada
cv_scores = cross_val_score(rf, X_train, y_train, cv=5)  

# Imprimir los resultados de la validación cruzada
print("Resultados de la validación cruzada:")
print(cv_scores)
print("Precisión promedio: {:.2f}".format(cv_scores.mean()))

# # Obtener la importancia de características
# importances = rf.feature_importances_

# # Crear un DataFrame con las características y su importancia
# df_importances = pd.DataFrame({'Feature': X.columns, 'Importance': importances})

# # Ordenar las características por importancia en orden descendente
# df_importances = df_importances.sort_values('Importance', ascending=False)
# important_features = df_importances['Feature'].head(10).tolist()
# # Imprimir las características ordenadas por importancia
# print(important_features)

Precisión del modelo: 1.0
Informe de clasificación:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        24
           1       1.00      1.00      1.00        53
           2       1.00      1.00      1.00        21

    accuracy                           1.00        98
   macro avg       1.00      1.00      1.00        98
weighted avg       1.00      1.00      1.00        98

Resultados de la validación cruzada:
[0.53846154 0.52564103 0.48717949 0.48717949 0.58441558]
Precisión promedio: 0.52


In [68]:
# Contar la cantidad de ejemplos en cada clase
class_counts = df_train['Cluster'].value_counts()

# Imprimir la distribución de clases
print("Distribución de clases:")
print(class_counts)


Distribución de clases:
Cluster
0    246
1    129
2    112
Name: count, dtype: int64


In [22]:
# Realizar validación cruzada
cv_scores = cross_val_score(rf, X, y, cv=5)

# Imprimir los resultados de la validación cruzada
print("Resultados de la validación cruzada:")
print(cv_scores)
print("Precisión promedio: {:.2f}".format(cv_scores.mean()))


Resultados de la validación cruzada:
[0.33673469 0.35714286 0.40206186 0.54639175 0.51546392]
Precisión promedio: 0.43


In [23]:
from sklearn.model_selection import GridSearchCV

# Definir la grilla de hiperparámetros a explorar
param_grid = {
    'n_estimators': [10,50, 100, 200],
    'max_depth': [None, 5, 7, 10, 12, 15,18],
    'min_samples_split': [2, 5, 10, 20]
}

# Realizar búsqueda en la grilla de hiperparámetros
grid_search = GridSearchCV(rf, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Obtener los mejores hiperparámetros encontrados
best_params = grid_search.best_params_
print("Mejores hiperparámetros:")
print(best_params)


Mejores hiperparámetros:
{'max_depth': None, 'min_samples_split': 5, 'n_estimators': 200}


In [24]:
from sklearn.metrics import classification_report, confusion_matrix

# Realizar predicciones en el conjunto de prueba
y_pred = rf.predict(X_test)

# Imprimir el informe de clasificación
print("Informe de clasificación:")
print(classification_report(y_test, y_pred))

# Imprimir la matriz de confusión
confusion_mat = confusion_matrix(y_test, y_pred)
print("Matriz de confusión:")
print(confusion_mat)


Informe de clasificación:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        24
           1       1.00      1.00      1.00        53
           2       1.00      1.00      1.00        21

    accuracy                           1.00        98
   macro avg       1.00      1.00      1.00        98
weighted avg       1.00      1.00      1.00        98

Matriz de confusión:
[[24  0  0]
 [ 0 53  0]
 [ 0  0 21]]


In [25]:
from sklearn.ensemble import RandomForestClassifier

# Crear el modelo de Random Forest con los hiperparámetros óptimos
rf_optimized = RandomForestClassifier(max_depth=18, min_samples_split=2, n_estimators=50, random_state=96)

# Entrenar el modelo con los datos de entrenamiento
rf_optimized.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred = rf_optimized.predict(X_test)

# Calcular la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo optimizado:", accuracy)

# Generar un nuevo informe de clasificación
report = classification_report(y_test, y_pred)
print("Nuevo informe de clasificación:")
print(report)

# Generar una nueva matriz de confusión
confusion_mat = confusion_matrix(y_test, y_pred)
print("Nueva matriz de confusión:")
print(confusion_mat)


Precisión del modelo optimizado: 0.6224489795918368
Nuevo informe de clasificación:
              precision    recall  f1-score   support

           0       0.67      0.42      0.51        24
           1       0.65      0.85      0.74        53
           2       0.43      0.29      0.34        21

    accuracy                           0.62        98
   macro avg       0.58      0.52      0.53        98
weighted avg       0.61      0.62      0.60        98

Nueva matriz de confusión:
[[10 10  4]
 [ 4 45  4]
 [ 1 14  6]]


In [40]:
# Realizar el perfilamiento de los clusters utilizando las características adicionales
perfilamiento_clusters = df_train.groupby('Cluster')[important_features].mean()

# Imprimir el perfilamiento de los clusters
print(perfilamiento_clusters)

         Tiempo_empresa       edad      JAVA  JOSE LUIS RODRIGUEZ_JEFE   
Cluster                                                                  
0            785.500000  31.598742  0.386179                  0.073171  \
1            767.550388  30.783100  0.418605                  0.170543   
2            729.580357  30.573166  0.276786                  0.160714   

          ANGULAR      .NET  FREDY SANDOVAL_JEFE  CO_639_PROY    ORACLE   
Cluster                                                                   
0        0.162602  0.105691             0.012195     0.020325  0.020325  \
1        0.147287  0.085271             0.015504     0.054264  0.069767   
2        0.089286  0.080357             0.089286     0.017857  0.035714   

         CARLOS URIBE_JEFE  
Cluster                     
0                 0.016260  
1                 0.038760  
2                 0.035714  


In [31]:
# Step 3: Initialize an empty set to collect unique words
word_set = set()

# Step 4: Iterate over each row in the DataFrame
for row in df_emb['Motivo_retiro']:
    # Step 5: Split the sentence into words and update the word_set
    words = row.split()
    word_set.update(words)

# Step 6: Convert the word_set to a list
word_list = list(word_set)

In [34]:
from sentence_transformers import SentenceTransformer, util

# Step 3: Load the SentenceTransformer model and generate the embedding for your target sentence or word
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

# Step 4: Define the target sentence
target_text = 'El motivo de retiro fue por salario'  # Example sentence

# Step 5: Split the sentence into individual words
target_words = target_text.split()

# Step 7: Find the nearest word for each word in the sentence
closest_words = []
for word in target_words:
    word_embedding = model.encode([word])
    cosine_similarities = util.pytorch_cos_sim(word_embedding, model.encode(word_list))
    closest_word_index = cosine_similarities.argmax().item()
    closest_word = word_list[closest_word_index]
    closest_words.append(closest_word)

# Step 8: Combine the closest words to form the updated sentence
updated_sentence = ' '.join(closest_words)

print("Updated sentence:", updated_sentence)


Updated sentence: El motivo de retiro fue por salario


In [4]:
import plotly.graph_objects as go
import pandas as pd

# Ejemplo de DataFrame con varias columnas
data = {
    'Columna1': [0, 1, 0, 1, 0],
    'Columna2': [1, 1, 0, 0, 1],
    'Columna3': [1, 0, 1, 0, 3],
    'Columna4': [1, 2, 2, 3, 4]
}

df = pd.DataFrame(data)

# Generar figuras separadas para cada columna
figures = []
for col in df.columns:
    value_counts = df[col].value_counts()
    x_values = value_counts.index.tolist()
    y_values = value_counts.values.tolist()
    
    fig = go.Figure(go.Bar(x=x_values, y=y_values))
    fig.update_layout(
        title=f'Cuenta de valores únicos - {col}',
        xaxis_title='Valores',
        yaxis_title='Cuenta',
    )
    
    figures.append(fig)

# Mostrar las figuras
for fig in figures:
    fig.show()
